config/routes.rb
ActiveAnalytics::Engine.routes.draw do
  get "/:site", to: "sites#show", as: :site, constraints: {site: /[^\/]+/}

  # Referrers
  get "/:site/referrers", to: "referrers#index", constraints: {site: /[^\/]+/}, as: :referrers
  get "/:site/referrers/:referrer", to: "referrers#show", constraints: {site: /[^\/]+/, referrer: /[^\/]+/}, as: :referrer

  # Pages
  get "/:site/pages", to: "pages#index", constraints: {site: /[^\/]+/}, as: :pages
  get "/:site/*page", to: "pages#show", as: :page, constraints: {site: /[^\/]+/}

  root to: "sites#index", as: :active_analytics
end

app/models/active_analytics/application_record.rb
module ActiveAnalytics
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/active_analytics/views_per_day.rb
module ActiveAnalytics
  class ViewsPerDay < ApplicationRecord
    validates_presence_of :site, :page, :date

    scope :between_dates, -> (from, to) { where("date BETWEEN ? AND ?", from, to) }
    scope :after, -> (date) { where("date > ?", date) }
    scope :order_by_totals, -> { order(Arel.sql("SUM(total) DESC")) }
    scope :order_by_date, -> { order(:date) }
    scope :top, -> (n = 10) { order_by_totals.limit(n) }

    class Site
      attr_reader :host, :total
      def initialize(host, total)
        @host, @total = host, total
      end
    end

    class Page
      attr_reader :host, :path, :total
      def initialize(host, path, total)
        @host, @path, @total = host, path, total
      end

      def url
        host + path
      end
    end

    class Day
      attr_reader :day, :total
      def initialize(day, total)
        @day, @total = day, total
      end
    end

    class Histogram
      attr_reader :bars, :from_date, :to_date

      def initialize(scope, from_date, to_date)
        @bars = scope.map { |day| Bar.new(day.day, day.total, self) }
        fill_missing_days(@bars, Date.parse(from_date.to_s), Date.parse(to_date.to_s))
      end

      def fill_missing_days(bars, from, to)
        i = 0
        while (day = from + i) <= to
          if !@bars[i] || @bars[i].label != day
            @bars.insert(i, Bar.new(day, 0, self))
          end
          i += 1
        end
        @bars
      end

      def max_value
        @max_total ||= bars.map(&:value).max
      end

      def total
        @bars.reduce(0) { |sum, bar| sum += bar.value }
      end

      class Bar
        attr_reader :label, :value, :histogram

        def initialize(label, value, histogram)
          @label, @value, @histogram = label, value, histogram
        end

        def height
          (value.to_f / histogram.max_value).round(2)
        end
      end
    end

    def self.group_by_site
      group(:site).pluck("site, SUM(total)").map do |row|
        Site.new(row[0], row[1])
      end
    end

    def self.group_by_page
      group(:site, :page).pluck("site, page, SUM(total)").map do |row|
        Page.new(row[0], row[1], row[2])
      end
    end

    def self.group_by_referrer_site
      group(:referrer_host).pluck("referrer_host, SUM(total)").map do |row|
        Site.new(row[0], row[1])
      end
    end

    def self.group_by_referrer_page
      group(:referrer_host, :referrer_path).pluck("referrer_host, referrer_path, SUM(total)").map do |row|
        Page.new(row[0], row[1], row[2])
      end
    end

    def self.group_by_date
      group(:date).pluck("date, SUM(total)").map do |row|
        Day.new(row[0], row[1])
      end
    end

    def self.to_histogram
      ViewsPerDay::Histogram.new(self)
    end

    def self.append(params)
      params[:site] = params[:site].downcase if params[:site]
      params[:page] = params[:page].downcase if params[:page]
      params[:referrer_path] = nil if params[:referrer_path].blank?
      params[:referrer_path] = params[:referrer_path].downcase if params[:referrer_path]
      params[:referrer_host] = params[:referrer_host].downcase if params[:referrer_host]
      find_or_create_by!(params) if where(params).update_all("total = total + 1") == 0
    end
  end
end

app/controllers/active_analytics/application_controller.rb
module ActiveAnalytics
  class ApplicationController < ActionController::Base

    private

    def require_date_range
      if Date.parse(params[:from]) > Date.parse(params[:to])
        redirect_to(params.to_unsafe_hash.merge(from: 7.days.ago.to_date, to: Date.today))
      end
    rescue TypeError, ArgumentError # Raise by Date.parse when invalid format
      redirect_to(params.to_unsafe_hash.merge(from: 7.days.ago.to_date, to: Date.today))
    end

    def current_views_per_days
      ViewsPerDay.where(site: params[:site]).between_dates(params[:from], params[:to])
    end
  end
end

app/controllers/active_analytics/pages_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class PagesController < ApplicationController
    include PagesHelper

    before_action :require_date_range

    def index
      scope = ViewsPerDay.where(site: params[:site]).between_dates(params[:from], params[:to])
      @histogram = ViewsPerDay::Histogram.new(scope.order_by_date.group_by_date, params[:from], params[:to])
      @pages = scope.top(100).group_by_page
    end

    def show
      dates_scopes = ViewsPerDay.between_dates(params[:from], params[:to])
      page_scope = dates_scopes.where(site: params[:site], page: page_from_params)
      @histogram = ViewsPerDay::Histogram.new(page_scope.order_by_date.group_by_date, params[:from], params[:to])
      @referrers = page_scope.top.group_by_referrer_site

      @next_pages = dates_scopes.where(referrer_host: params[:site], referrer_path: page_from_params).top(100).group_by_page
      @previous_pages = dates_scopes.where(site: params[:site], page: page_from_params).where.not(referrer_path: nil).top(100).group_by_referrer_page
    end
  end
end

app/controllers/active_analytics/referrers_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class ReferrersController < ApplicationController
    before_action :require_date_range

    def index
      scope = ViewsPerDay.where(site: params[:site]).between_dates(params[:from], params[:to])
      @referrers = scope.top(100).group_by_referrer_site
      @histogram = ViewsPerDay::Histogram.new(scope.order_by_date.group_by_date, params[:from], params[:to])
    end

    def show
      scope = ViewsPerDay.where(site: params[:site], referrer_host: params[:referrer]).between_dates(params[:from], params[:to])
      @histogram = ViewsPerDay::Histogram.new(scope.order_by_date.group_by_date, params[:from], params[:to])
      @previous_pages = scope.top(100).group_by_referrer_page
      @next_pages = scope.top(100).group_by_page
    end
  end
end

app/controllers/active_analytics/sites_controller.rb
require_dependency "active_analytics/application_controller"

module ActiveAnalytics
  class SitesController < ApplicationController
    before_action :require_date_range, only: :show

    def index
      @sites = ViewsPerDay.after(30.days.ago).order_by_totals.group_by_site
      redirect_to(site_path(@sites.first.host)) if @sites.size == 1
    end

    def show
      scope = current_views_per_days
      @histogram = ViewsPerDay::Histogram.new(scope.order_by_date.group_by_date, params[:from], params[:to])
      @referrers = scope.top.group_by_referrer_site
      @pages = scope.top.group_by_page
    end
  end
end

app/helpers/active_analytics/application_helper.rb
module ActiveAnalytics
  module ApplicationHelper
    def format_view_count(number)
      number_with_delimiter(number.to_i)
    end
  end
end

app/helpers/active_analytics/page_views_helper.rb
module ActiveAnalytics
  module PageViewsHelper
  end
end

app/helpers/active_analytics/pages_helper.rb
module ActiveAnalytics
  module PagesHelper
    def page_to_params(name)
      name == "/" ? "index" : name[1..-1]
    end

    def page_from_params
      if params[:page] == "index"
        "/"
      elsif params[:page].present?
        "/#{params[:page]}"
      end
    end
  end
end

app/helpers/active_analytics/referrers_helper.rb
module ActiveAnalytics
  module ReferrersHelper
  end
end

app/helpers/active_analytics/sites_helper.rb
module ActiveAnalytics
  module SitesHelper
    def site_icon(host)
      image_tag("https://icons.duckduckgo.com/ip3/#{host}.ico", referrerpolicy: "no-referrer", class: "referer-favicon")
    end
  end
end

app/views/active_analytics/page_views/show.html.erb
<section>
  <h2>Views per day</h2>
  <table>
    <% for views in @views_per_day %>
      <tr>
        <td><%= l views.day %></td>
        <td><%= views.total %></td>
      </tr>
    <% end %>
  </table>
</section>

<section>
  <h2>Top Pages</h2>
  <table>
    <% for page in @pages %>
      <tr>
        <td><%= link_to page.path, page_view_path(site: page.host) + page.path %></td>
        <td><%= page.total %></td>
      </tr>
    <% end %>
  </table>
</section>

<section>
  <h2>Top referers</h2>
  <table>
    <% for referer in @referers %>
      <tr>
        <td><%= referer.host %></td>
        <td><%= referer.total %></td>
      </tr>
    <% end %>
  </table>
</section>

app/views/active_analytics/pages/_table.html.erb
<% if pages.empty? %>
  <div class="is-empty">
    <span>no data</span>
  </div>
<% else %>
  <table>
    <% for page in pages %>
      <tr>
        <td>
          <% if page.host == params[:site] %>
            <% if page.path.present? %>
              <%= link_to page.path, page_path(site: page.host, page: page_to_params(page.path), from: params[:from], to: params[:to]) %>
            <% else %>
              <%= site_icon page.host %>
              <%= link_to page.host, site_path(site: page.host, from: params[:from], to: params[:to]) %>
              <small>(page not provided <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#strict-origin-when-cross-origin">?</a>)</small>
            <% end %>
          <% elsif page.host.present? && page.path.present? %>
            <%= link_to(referrer_path(site: params[:site], referrer: page.host, from: params[:from], to: params[:to])) { site_icon page.host } %>
            <%= link_to page.url, referrer_path(site: params[:site], referrer: page.host, from: params[:from], to: params[:to]) %>
          <% elsif page.host.present? %>
            <%= site_icon page.host %>
            <%= page.host %>
          <% else %>
            (None or direct)
          <% end %>
        </td>
        <td class="number"><%= format_view_count page.total %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/active_analytics/pages/index.html.erb
<section class="card">
  <h3><%= format_view_count @histogram.total %> views</h3>
  <%= render "/active_analytics/sites/histogram", histogram: @histogram %>
</section>

<section class="card">
  <h3>Top pages</h3>
  <%= render "/active_analytics/pages/table", pages: @pages %>
</section>

app/views/active_analytics/pages/show.html.erb
<section>
  <h2><%= page_from_params %></h2>
</section>

<section class="card">
  <h3><%= format_view_count @histogram.total %> views</h3>
  <%= render "/active_analytics/sites/histogram", histogram: @histogram %>
</section>

<ul class="grid-auto">
  <li class="card">
    <section>
      <h3>Previous page</h3>
      <%= render "table", pages: @previous_pages %>
    </section>
  </li>

  <li class="card">
    <h3>Next page</h3>
    <%= render "table", pages: @next_pages %>
  </li>
</ul>

app/views/active_analytics/referrers/_table.html.erb
<% if referrers.empty? %>
  <div class="is-empty">
    <span>no data</span>
  </div>
<% else %>
  <table>
    <% for referrer in referrers %>
      <tr>
        <td>
          <% if referrer.host %>
            <%= site_icon referrer.host %>
            <%= link_to referrer.host, referrer_path(site: params[:site], referrer: referrer.host, from: params[:from], to: params[:to]) %>
          <% else %>
            <%= referrer.host %>
          <% end %>
          </td>
        <td class="number"><%= format_view_count referrer.total %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/active_analytics/referrers/index.html.erb
<section class="card">
  <h3><%= format_view_count @histogram.total %> views</h3>
  <%= render "/active_analytics/sites/histogram", histogram: @histogram %>
</section>

<section class="card">
  <h3>Top sources</h3>
  <%= render "table", referrers: @referrers %>
</section>

app/views/active_analytics/referrers/show.html.erb
<section>
  <h2>Source: <%= params[:referrer] %></h2>
</section>

<section class="card">
  <h3><%= format_view_count @histogram.total %> views</h3>
  <%= render "/active_analytics/sites/histogram", histogram: @histogram %>
</section>
<ul class="grid-auto">
  <li class="card">
    <h3>Source page</h3>
    <%= render "/active_analytics/pages/table", pages: @previous_pages %>
  </li>

  <li class="card">
    <h3>Destination page</h3>
    <%= render "/active_analytics/pages/table", pages: @next_pages %>
  </li>
</ul>

app/views/active_analytics/sites/_histogram.html.erb
<% if histogram.bars.count > 1 %>
  <table class="charts-css column show-primary-axis show-5-secondary-axes hide-data <%= "show-labels" if histogram.bars.count < 32 %>" style="height: calc(var(--space-2x) * 8);">
    <tbody>
      <% for bar in histogram.bars %>
        <tr>
          <th scope="row"><%= bar.label.day %></td>
            <td style="--size: <%= bar.height %>; --color: rgba(var(--color-grey-100), 1);">
            <span class="data"><%= bar.value.to_i %></span>
            <span class="tooltip"><small class="tooltip-date"><%= l bar.label, format: :long%></small><br/><%= format_view_count bar.value %> views</span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/active_analytics/sites/index.html.erb
<h2>Site views in the last 30 days</h2>
<div class="card">
  <table>
    </tr>
    <% for site in @sites %>
      <tr>
        <td><%= link_to site.host, site_path(site: site.host) %></td>
        <td class="number"><%= format_view_count site.total %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/active_analytics/sites/show.html.erb
<section class="card">
  <h3><%= format_view_count @histogram.total %> views</h3>
  <%= render "/active_analytics/sites/histogram", histogram: @histogram %>
</section>

<ul class="grid-auto">
  <li class="card">
    <h3>Top sources <%= link_to "view all", referrers_path(from: params[:from], to: params[:to]) %></h3>
    <%= render "/active_analytics/referrers/table", referrers: @referrers %>
  </li>

  <li class="card">
    <h3>Top pages <%= link_to "view all", pages_path(from: params[:from], to: params[:to]) %></h3>
    <%= render "/active_analytics/pages/table", pages: @pages %>
  </li>
</ul>

app/views/layouts/active_analytics/_footer.html.erb
<footer>
  <p>
    Made in <a href="https://www.basesecrete.com" target="_blank" rel="noopener">Base Secrète</a> | <%= link_to "Source code", "https://github.com/BaseSecrete/active_analytics", target: "_blank", rel: "noopener" %> | <%= link_to "Twitter", "https://twitter.com/base_secrete", target: "_blank", rel: "noopener" %>
  </p>
  
  <div class="card">
    <ul class="grid-auto">
      <li>
        <a href="https://github.com/BaseSecrete/rorvswild" target="_blank" rel="noopener">RoRvsWild</a>
        <p>Ruby on Rails application performances and exceptions monitoring.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/redis_dashboard" target="_blank" rel="noopener">Redis Dashboard</a>
        <p>Sinatra app to monitor Redis servers.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/type_scopes" target="_blank" rel="noopener">Type Scopes</a>
        <p>Automatic scopes for ActiveRecord models.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/secure_attribute" target="_blank" rel="noopener">Secure Attribute</a>
        <p>Encrypt attributes of any Ruby object or ActiveRecord model.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/teamodoro" target="_blank" rel="noopener">Teamodoro</a>
        <p>Synchronize pomodoros with your coworkers.</p>
      </li>
      <li>
        <a href="https://github.com/BaseSecrete/ariato" target="_blank" rel="noopener">Ariato</a>
        <p>Web UI framework to improve accessibility.</p>
      </li>
    </ul>
  </div>
</footer>

<div role="dialog" hidden="true" id="custom-date-range" aria-labelledby="custom-range-title" aria-modal="true">
  <header id="custom-range-title">Custom range</header>
  <%= form_tag url_for(params.except(:from, :to).to_unsafe_hash), method: "get", id: "dateRangeForm" do %>
    <div role="group" class="is-block">
      <label>From <%= text_field_tag :from, params[:from] %></label>
      <label>To <%= text_field_tag :to, params[:to] %></label>
    </div>
  <% end %>
  <footer>
    <%= submit_tag "Change date range", form: "dateRangeForm" %>
    <button type="reset" onclick="Ariato.Dialog.close(this)">Close</button>
  </footer>
</div>

app/views/layouts/active_analytics/_header.html.erb
<header data-ariato="ActiveAnalytics.Header">
  <nav aria-label="site"> <!-- implicit role="navigation", aria label "site" is announced = "site navigation" -->
    
    <%#= link_to "Analytics", active_analytics_path, role: "button" %>
    <%= link_to active_analytics_path, class: 'logo' do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11 11">
        <path class="a" d="M.5,5.5s0,2,1,2,1-2,1-2,0-2,1-2,1,2,1,2,0,2,1,2,1-2,1-2,0-2,1-2,1,2,1,2,0,2,1,2,1-2,1-2"/>
        <circle class="a" cx="5.5" cy="5.5" r="5"/>
        <line class="a" x1="0.5" y1="5.5" x2="10.5" y2="5.5"/>
      </svg>
    <% end %>

    <% if params[:site] %>
      <%= link_to params[:site], site_path(params[:site], from: params[:from], to: params[:to]) %>
      
      <% if controller_name == "pages" %>
        &nbsp;/&nbsp;<%= link_to "pages", pages_path(params[:site], from: params[:from], to: params[:to]) %>
      <% end %>

      <% if controller_name == "referrers" %>
        &nbsp;/&nbsp;<%= link_to "referrers", referrers_path(params[:site], from: params[:from], to: params[:to]) %>
      <% end %>

      <div class="menubutton">
        <button type="button" id="date-range" aria-haspopup="true" aria-controls="date-range-menu">
          <%= l params[:from].to_date, format: :long %>
          <% if params[:to].to_date !=  params[:from].to_date %> → <%= l params[:to].to_date, format: :long %><% end%>
        </button>
        <ul id="date-range-menu" role="menu" aria-labelledby="date-range">
          <li role="none">
            <%= link_to "Today", url_for(params.merge(from: Date.today, to: Date.today).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <%= link_to "Yesterday", url_for(params.merge(from: Date.yesterday, to: Date.yesterday).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <%= link_to "Last 7 days", url_for(params.merge(from: 7.days.ago.to_date, to: Date.today).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <%= link_to "Last 30 days", url_for(params.merge(from: 30.days.ago.to_date, to: Date.today).to_unsafe_hash), role: "menuitem", tabindex: "-1" %>
          </li>
          <li role="none">
            <button type="button" onclick="Ariato.Dialog.open('custom-date-range')"  tabindex="-1" class="is-link">
              Custom range
            </button>
          </li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/active_analytics/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Active analytics</title>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "active_analytics/application", media: "all" %>
    <%= javascript_include_tag "active_analytics/application" %>
  </head>

  <body>
    <%= render "/layouts/active_analytics/header" %>
    <main aria-label="Content">
      <%= yield %>
    </main>
    <%= render "/layouts/active_analytics/footer" %>
  </body>
</html>